#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : llvm12-32
Version  : 12.0.0.rc3
Release  : 1
URL      : file:///insilications/apps/llvm-12.0.0-rc3.tar.gz
Source0  : file:///insilications/apps/llvm-12.0.0-rc3.tar.gz
Summary  : Google microbenchmark framework
Group    : Development/Tools
License  : Apache-2.0
Requires: graphviz
Requires: matplotlib
Requires: pandas
Requires: psutil
Requires: ptyprocess
Requires: seaborn
BuildRequires : Sphinx
BuildRequires : Vulkan-Headers-dev Vulkan-Loader-dev Vulkan-Tools
BuildRequires : Z3-dev
BuildRequires : Z3-dev32
BuildRequires : Z3-staticdev
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : cmake
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : elfutils-dev32
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-lib-avx2
BuildRequires : glibc-libc32
BuildRequires : glibc-staticdev
BuildRequires : glibc-utils
BuildRequires : googletest-dev
BuildRequires : graphviz
BuildRequires : grep
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libffi-dev
BuildRequires : libffi-dev32
BuildRequires : libffi-staticdev
BuildRequires : libffi-staticdev32
BuildRequires : libstdc++-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-dev32
BuildRequires : libxml2-staticdev
BuildRequires : libxml2-staticdev32
BuildRequires : lua-dev
BuildRequires : matplotlib
BuildRequires : ncurses-dev
BuildRequires : ncurses-dev32
BuildRequires : ninja
BuildRequires : pandas
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(32libffi)
BuildRequires : pkgconfig(libedit)
BuildRequires : pkgconfig(libffi)
BuildRequires : protobuf-dev
BuildRequires : psutil
BuildRequires : ptyprocess
BuildRequires : pybind11-python3
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : seaborn
BuildRequires : sed
BuildRequires : swig
BuildRequires : valgrind-dev
BuildRequires : xz-dev
BuildRequires : xz-dev32
BuildRequires : xz-staticdev
BuildRequires : xz-staticdev32
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
BuildRequires : zlib-staticdev
BuildRequires : zlib-staticdev32
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Make-default-to-skylake.patch
Patch2: 0002-Introduce-the-flag-which-allows-not-to-shrink-lines.patch

%description
Polly - Polyhedral optimizations for LLVM
-----------------------------------------
http://polly.llvm.org/

%prep
%setup -q -n llvm-12.0.0-rc3
cd %{_builddir}/llvm-12.0.0-rc3
%patch1 -p1
%patch2 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1617163893
unset LD_AS_NEEDED
mkdir -p clr-build32
pushd clr-build32
## altflags1_32 content
unset LD_LIBRARY_PATH
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
unset CCACHE_DISABLE
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#
unset LDFLAGS
unset CFLAGS
unset CXXFLAGS
unset FCFLAGS
unset FFLAGS
#
export CFLAGS="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -pipe -fPIC"
#
export CXXFLAGS="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -fPIC"
#
export FCFLAGS="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -pipe -fPIC"
#
export FFLAGS="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -pipe -fPIC"
#
export LDFLAGS="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -pipe -fPIC"
#
export V=1
export VERBOSE=1
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
## altflags1_32 end
cmake ../llvm -G Ninja \
-DCMAKE_INSTALL_LIBDIR=/usr/lib32 \
-DCMAKE_INSTALL_PREFIX=/usr \
-DLIB_INSTALL_DIR:PATH=/usr/lib32 \
-DLIB_SUFFIX=32 \
-DLLVM_LIBDIR_SUFFIX=32 \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DCLANG_DEFAULT_CXX_STDLIB="libstdc++" \
-DLLVM_STATIC_LINK_CXX_STDLIB:BOOL=ON \
-DLLVM_ENABLE_ASSERTIONS:BOOL=ON \
-DCLANG_DEFAULT_RTLIB="libgcc" \
-DCLANG_DEFAULT_UNWINDLIB="libgcc" \
-DLLVM_TARGETS_TO_BUILD="host;AMDGPU" \
-DCLANG_LINK_CLANG_DYLIB:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=OFF \
-DLLVM_BUILD_LLVM_DYLIB:BOOL=ON \
-DCMAKE_AR=/usr/bin/gcc-ar \
-DCMAKE_NM=/usr/bin/gcc-nm \
-DCMAKE_RANLIB=/usr/bin/gcc-ranlib \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_COMPILER=gcc \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_JOB_POOLS="full_jobs=10" \
-DCMAKE_JOB_POOL_COMPILE="full_jobs" \
-DCMAKE_JOB_POOL_LINK="full_jobs" \
-DLLVM_ENABLE_PROJECTS="llvm;clang;parallel-libs;polly;pstl" \
-DCMAKE_C_FLAGS_RELEASE="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -pipe -fPIC" \
-DCMAKE_CXX_FLAGS_RELEASE="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -fPIC" \
-DCMAKE_EXE_LINKER_FLAGS_RELEASE="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -pipe -fPIC" \
-DCMAKE_MODULE_LINKER_FLAGS_RELEASE="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -pipe -fPIC" \
-DCMAKE_SHARED_LINKER_FLAGS_RELEASE="-m32 -mstackrealign -fomit-frame-pointer -fexceptions -Wl,--as-needed -fno-lto -fuse-ld=bfd -fuse-linker-plugin -fno-lto -ffat-lto-objects -Wl,--build-id=sha1 -Wno-error -Wl,-z,max-page-size=0x1000 -O3 -march=native -mtune=native -Wall -Wl,--enable-new-dtags -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -malign-data=cacheline -Wl,-sort-common -Wp,-D_REENTRANT -pipe -fPIC" \
-DENABLE_LINKER_BUILD_ID:BOOL=ON \
-DFFI_INCLUDE_DIR=`pkg-config --variable=includedir libffi` \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_BUILD_EXAMPLES:BOOL=OFF \
-DLLVM_BUILD_RUNTIME:BOOL=ON \
-DLLVM_BUILD_TOOLS:BOOL=OFF \
-DCLANG_BUILD_TOOLS:BOOL=OFF \
-DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD:BOOL=OFF \
-DLLVM_TOOL_CLANG_BUILD:BOOL=OFF \
-DLLVM_TOOL_COMPILER_RT_BUILD:BOOL=OFF \
-DLLVM_TOOL_LLD_BUILD:BOOL=OFF \
-DLLVM_TOOL_OPENMP_BUILD:BOOL=OFF \
-DLIBCLANG_BUILD_STATIC:BOOL=ON \
-DLLVM_INCLUDE_TOOLS:BOOL=OFF \
-DLLVM_ENABLE_BINDINGS:BOOL=OFF \
-DLLVM_ENABLE_FFI:BOOL=ON \
-DLLVM_ENABLE_LIBCXX:BOOL=OFF \
-DLLVM_ENABLE_PIC=ON \
-DLLVM_ENABLE_RTTI:BOOL=ON \
-DLLVM_ENABLE_EH:BOOL=ON \
-DLLVM_ENABLE_ZLIB:BOOL=ON \
-DLLVM_ENABLE_Z3_SOLVER:BOOL=ON \
-DLLVM_ENABLE_LIBXML2:BOOL=ON \
-DCLANG_ENABLE_STATIC_ANALYZER:BOOL=OFF \
-DLLVM_HOST_TRIPLE="i686-generic-linux" \
-DLLVM_INCLUDE_TESTS:BOOL=OFF \
-DCLANG_INCLUDE_TESTS:BOOL=OFF \
-DLLVM_INSTALL_UTILS:BOOL=OFF \
-DLLVM_OPTIMIZED_TABLEGEN:BOOL=ON \
-DLLVM_REQUIRES_RTTI:BOOL=ON \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-DLLVM_BUILD_32_BITS:BOOL=ON \
-Wno-dev
ninja  %{?_smp_mflags}  --verbose all
## ccache stats
ccache -s
## ccache stats
unset PKG_CONFIG_PATH
popd

%install
export SOURCE_DATE_EPOCH=1617163893
rm -rf %{buildroot}
pushd clr-build32
%ninja_install32  install all
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
## install_append content
#pushd %{buildroot}/usr/lib64
#mkdir -p ../lib/bfd-plugins
#ln -s ../../lib64/LLVMgold.so ../lib/bfd-plugins
#popd
## install_append end

%files
%defattr(-,root,root,-)
